# Generated by Django 4.2 on 2024-02-15 23:24

import app.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=60, validators=[app.utils.validators.validate_first_letter, app.utils.validators.validate_letters], verbose_name='Title')),
                ('description', models.TextField(max_length=200, validators=[app.utils.validators.validate_first_letter], verbose_name='Description')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[app.utils.validators.validate_value], verbose_name='Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, validators=[app.utils.validators.validate_date], verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, validators=[app.utils.validators.validate_date], verbose_name='Updated Date')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('situation', models.CharField(choices=[('W', 'Waiting'), ('O', 'Open'), ('B', 'Busy'), ('F', 'Finished')], default='W', max_length=1, validators=[app.utils.validators.validate_letters], verbose_name='Project Situation')),
                ('payment_type', models.CharField(max_length=20, validators=[app.utils.validators.validate_first_letter], verbose_name='Payment Type')),
                ('area', models.CharField(max_length=2, validators=[app.utils.validators.validate_letters], verbose_name='Project Area')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cover_letter', models.TextField(blank=True, max_length=200, verbose_name='Letter')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Project')),
                ('situation', models.CharField(choices=[('W', 'Waiting'), ('I', 'Interest'), ('S', 'Signed')], default='W', max_length=1, validators=[app.utils.validators.validate_first_letter], verbose_name='Situation')),
                ('is_paid', models.BooleanField(default=False)),
                ('discounted_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[app.utils.validators.validate_value], verbose_name='Discounted Value')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted Date')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Paid Date')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='app.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
    ]
