# Generated by Django 4.2 on 2024-02-16 01:37

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(choices=[('FS', 'Full-Stack'), ('FE', 'Front-End'), ('BE', 'Back-End'), ('GM', 'Gaming')], max_length=2, validators=[app.utils.validators.validate_letters], verbose_name='Project Area'),
        ),
    ]
