# Generated by Django 4.2 on 2024-02-16 17:19

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=200, validators=[app.utils.validators.validate_first_letter, app.utils.validators.validate_safe_text], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=60, validators=[app.utils.validators.validate_first_letter, app.utils.validators.validate_letters, app.utils.validators.validate_safe_text], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='discounted_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[app.utils.validators.validate_value], verbose_name='Discounted Value'),
        ),
    ]
