# Generated by Django 4.2 on 2024-02-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_description_alter_project_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='discounted_value',
        ),
    ]
